// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using NotificationService.Repository.Context;
using System;

namespace NotificationService.Repository.Migrations
{
    [DbContext(typeof(NotificationContext))]
    [Migration("20180322093416_fix1")]
    partial class fix1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Notification")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("NotificationService.Shared.Data.Notification", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnName("body");

                    b.Property<string>("Channel")
                        .HasColumnName("chanel");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnName("created_date");

                    b.Property<bool>("IsReaded")
                        .HasColumnName("isreaded");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnName("modify_date");

                    b.Property<int?>("ProtocolId")
                        .IsRequired();

                    b.Property<string>("Receiver")
                        .HasColumnName("receiver");

                    b.Property<string>("Title")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ProtocolId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("NotificationService.Shared.Data.NotificationProtocol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("protocol_id");

                    b.Property<string>("Protocol")
                        .HasColumnName("protocol");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("notification_protocol");
                });

            modelBuilder.Entity("NotificationService.Shared.Data.Notification", b =>
                {
                    b.HasOne("NotificationService.Shared.Data.NotificationProtocol", "Protocol")
                        .WithMany("Notifications")
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
